### ISSUE TITLE
Cannot test Bot Related Features on preview domains

### ISSUE THREAD

**Issue by bjesuiter** [codemonument/deno_audio_logbook#23]
I cannot test bot-related features on preview domains. 
Therefore idea: 

1. Adding a FlexDNS domain on one of my domains 
2. Updating the target for the FlexDNS Domain every time a new preview deployment goes online
   CAUTION: This would every time connect the newest preview deployment with the url, 
   regardless of who pushed the last preview deployments. => We simply have to keep that in mind. 
   => Good: We can detect, which deno ID is used for our preview url by simply looking at the deployment id in the footer :D 
3. Create a clone of the deno-audio-logbook bot, name it deno-audio-logbook-preview and link it to this new preview domain

**Comment by bjesuiter** [comment]
Problem: Flex DNS only updates IP Adresses, not C-Names. :/ 
Need another api for updating c-names

**Comment by bjesuiter** [comment]
Have a new Approach: a completely cloned preview deployment on deno deploy , together with a cloned bot.

**Comment by Bloodiko** [comment]
Closed , since fixed with #25 

(If you add "fixes and or closes #23" next time within the fixing commit, it will auto close issues on merge @bjesuiter )

**Comment by bjesuiter** [comment]
Yeah, wanted to do it, but a comment in the PR does not seem to be enough 😞
