### ISSUE TITLE
Preview Bot Login Widget fails to show up 80% of reloads

### ISSUE THREAD

**Issue by bjesuiter** [codemonument/deno_audio_logbook#26]
I've a strange error with the preview bot page at: 
https://deno-audio-logbook-preview.deno.dev/auth/login

State: I'm NOT logged in 

1. I open the url: https://deno-audio-logbook-preview.deno.dev/auth/login
Result: 
<img width="897" alt="Bildschirmfoto 2023-04-06 um 21 23 35" src="https://user-images.githubusercontent.com/2365676/230475375-b50c8a7b-0bbf-4254-8576-e3c14bcc9b5d.png">

2. I klick nothing and reload the page 2 - 10. times 

## Observation 

Sometimes the widget loads and some time it doesn't. 

Screenshot when it doesn't load: 
<img width="897" alt="Bildschirmfoto 2023-04-06 um 21 25 31" src="https://user-images.githubusercontent.com/2365676/230475771-60d9881f-5909-466e-8f1a-941c864547b4.png">

## Other Things tried 

I tried to replicate that bug with the main url: https://deno-audio-logbook.deno.dev/auth/login
But even after 10 tries, the widget is shown every time. 

<img width="1904" alt="Bildschirmfoto 2023-04-06 um 21 26 52" src="https://user-images.githubusercontent.com/2365676/230476016-91134b38-f2ad-4900-aa95-014119be81df.png">

**Comment by Bloodiko** [comment]
![image](https://user-images.githubusercontent.com/21989414/230484995-5acb0844-8256-400f-aa94-36507c14ba7e.png)
Request seems to be cancelled by SOMETHING, 

But i cannot seem to find a pattern, why and when

**Comment by bjesuiter** [comment]
Probable Explanation: 

The TelegramLogin Island Component will be server rendered, sent to the client and then hydrated with preact. 
Before hydration, the server render will successfully load the telegram login iframe, but as soon as preact gets hydrated, it overwrites the dom inside itself, basically killing the iframe
